version: '3.1'

services:
  api:
    build: ./backend
    container_name: backend
    ports:
      - 3333:3333
    depends_on:
       database:
        condition: service_healthy
    environment:
      - PORT=3333
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=TaskManager
      - MYSQL_PORT=3306

    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3306"]
      timeout: 10s
      retries: 5
  
  database:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
  
  web:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3333"]
      timeout: 10s
      retries: 5